- name: Acte 1 - Configuration d'interfaces sur csr1000
  # On va agir sur l'hôte csr1000 dans cet acte
  hosts: csr1000
  # Passe l'étape permettant de récupérer des informations sur
  #   l'hôte pour gagner du temps
  gather_facts: false
  # Liste des tâches associées à notre Acte
  tasks:
    - name: Configuration de l'interface Gigabit 1
      cisco.ios.ios_l3_interfaces:
        config :
          - name: GigabitEthernet1
            ipv4:
#            description: "Interface par dhcp"
              - dhcp:
                  enable: true

    - name: Configuration de l'interface Gigabit 2
      cisco.ios.ios_l3_interfaces:
        config :
        - name: GigabitEthernet2
#        description: "Interface réseau 192.168.2.0/24"
          ipv4:
            - address: 192.168.2.1/24
        state: merged

    - name: Configuration de l'interface Gigabit 3
      cisco.ios.ios_l3_interfaces:
        config :
        - name: GigabitEthernet3
#        description: "Interface réseau 192.168.3.0/24"
          ipv4:
            - address: 192.168.3.1/24
        state: merged

    - name: Configuration de l'interface Gigabit 4
      cisco.ios.ios_l3_interfaces:
        config :
        - name: GigabitEthernet4
#        description: "Interface réseau 192.168.4.0/24"
          ipv4:
            - address: 192.168.4.1/24
        state: merged
